// country-info.js — Fiche signalétique par pays (capitale, population, langues, continent).
// Données au meilleur de nos connaissances (populations arrondies, ordre de grandeur récent).
export const COUNTRY_INFO = {
  'AD': { capital: 'Andorre-la-Vieille', population: 0.08, languages: 'Catalan', continent: 'Europe' },
  'AE': { capital: 'Abou Dabi', population: 9.9, languages: 'Arabe', continent: 'Asie' },
  'AF': { capital: 'Kaboul', population: 40.1, languages: 'Pashto, Dari', continent: 'Asie' },
  'AG': { capital: "Saint John's", population: 0.1, languages: 'Anglais', continent: 'Amérique du Nord' },
  'AL': { capital: 'Tirana', population: 2.8, languages: 'Albanais', continent: 'Europe' },
  'AM': { capital: 'Erevan', population: 2.8, languages: 'Arménien', continent: 'Asie' },
  'AO': { capital: 'Luanda', population: 35.6, languages: 'Portugais', continent: 'Afrique' },
  'AR': { capital: 'Buenos Aires', population: 45.8, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'AT': { capital: 'Vienne', population: 9.1, languages: 'Allemand', continent: 'Europe' },
  'AU': { capital: 'Canberra', population: 26.0, languages: 'Anglais', continent: 'Océanie' },
  'AZ': { capital: 'Bakou', population: 10.4, languages: 'Azéri', continent: 'Asie' },
  'BA': { capital: 'Sarajevo', population: 3.2, languages: 'Bosnien, Croate, Serbe', continent: 'Europe' },
  'BB': { capital: 'Bridgetown', population: 0.3, languages: 'Anglais', continent: 'Amérique du Nord' },
  'BD': { capital: 'Dacca', population: 173.0, languages: 'Bengali', continent: 'Asie' },
  'BE': { capital: 'Bruxelles', population: 11.7, languages: 'Néerlandais, Français, Allemand', continent: 'Europe' },
  'BF': { capital: 'Ouagadougou', population: 22.7, languages: 'Français', continent: 'Afrique' },
  'BG': { capital: 'Sofia', population: 6.4, languages: 'Bulgare', continent: 'Europe' },
  'BH': { capital: 'Manama', population: 1.5, languages: 'Arabe', continent: 'Asie' },
  'BI': { capital: 'Bujumbura', population: 12.9, languages: 'Français, Kirundi', continent: 'Afrique' },
  'BJ': { capital: 'Porto-Novo', population: 13.4, languages: 'Français', continent: 'Afrique' },
  'BN': { capital: 'Bandar Seri Begawan', population: 0.45, languages: 'Malais', continent: 'Asie' },
  'BO': { capital: 'La Paz', population: 12.2, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'BR': { capital: 'Brasília', population: 216.4, languages: 'Portugais', continent: 'Amérique du Sud' },
  'BS': { capital: 'Nassau', population: 0.4, languages: 'Anglais', continent: 'Amérique du Nord' },
  'BT': { capital: 'Thimphou', population: 0.8, languages: 'Dzongkha', continent: 'Asie' },
  'BW': { capital: 'Gaborone', population: 2.6, languages: 'Anglais, Tswana', continent: 'Afrique' },
  'BY': { capital: 'Minsk', population: 9.4, languages: 'Biélorusse, Russe', continent: 'Europe' },
  'BZ': { capital: 'Belmopan', population: 0.4, languages: 'Anglais', continent: 'Amérique du Nord' },
  'CA': { capital: 'Ottawa', population: 39.0, languages: 'Anglais, Français', continent: 'Amérique du Nord' },
  'CD': { capital: 'Kinshasa', population: 102.3, languages: 'Français', continent: 'Afrique' },
  'CG': { capital: 'Brazzaville', population: 5.8, languages: 'Français', continent: 'Afrique' },
  'CH': { capital: 'Berne', population: 8.8, languages: 'Allemand, Français, Italien', continent: 'Europe' },
  'CI': { capital: 'Abidjan', population: 29.4, languages: 'Français', continent: 'Afrique' },
  'CL': { capital: 'Santiago', population: 19.6, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'CM': { capital: 'Yaoundé', population: 27.9, languages: 'Français, Anglais', continent: 'Afrique' },
  'CN': { capital: 'Pékin', population: 1412.0, languages: 'Mandarin', continent: 'Asie' },
  'CO': { capital: 'Bogota', population: 52.1, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'CR': { capital: 'San José', population: 5.2, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'CU': { capital: 'La Havane', population: 11.2, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'CV': { capital: 'Praia', population: 0.6, languages: 'Portugais', continent: 'Afrique' },
  'CY': { capital: 'Nicosie', population: 1.2, languages: 'Grec, Turc', continent: 'Asie' },
  'CZ': { capital: 'Prague', population: 10.5, languages: 'Tchèque', continent: 'Europe' },
  'DE': { capital: 'Berlin', population: 84.5, languages: 'Allemand', continent: 'Europe' },
  'DJ': { capital: 'Djibouti', population: 1.1, languages: 'Français, Arabe', continent: 'Afrique' },
  'DK': { capital: 'Copenhague', population: 5.9, languages: 'Danois', continent: 'Europe' },
  'DM': { capital: 'Roseau', population: 0.07, languages: 'Anglais', continent: 'Amérique du Nord' },
  'DO': { capital: 'Saint-Domingue', population: 11.3, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'DZ': { capital: 'Alger', population: 45.4, languages: 'Arabe', continent: 'Afrique' },
  'EC': { capital: 'Quito', population: 18.0, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'EE': { capital: 'Tallinn', population: 1.3, languages: 'Estonien', continent: 'Europe' },
  'EG': { capital: 'Le Caire', population: 112.7, languages: 'Arabe', continent: 'Afrique' },
  'ER': { capital: 'Asmara', population: 3.7, languages: 'Tigrigna, Arabe', continent: 'Afrique' },
  'ES': { capital: 'Madrid', population: 47.6, languages: 'Espagnol', continent: 'Europe' },
  'ET': { capital: 'Addis-Abeba', population: 126.5, languages: 'Amharique', continent: 'Afrique' },
  'FI': { capital: 'Helsinki', population: 5.6, languages: 'Finnois, Suédois', continent: 'Europe' },
  'FJ': { capital: 'Suva', population: 0.9, languages: 'Anglais, Fidjien', continent: 'Océanie' },
  'FM': { capital: 'Palikir', population: 0.1, languages: 'Anglais', continent: 'Océanie' },
  'FR': { capital: 'Paris', population: 68.2, languages: 'Français', continent: 'Europe' },
  'GA': { capital: 'Libreville', population: 2.4, languages: 'Français', continent: 'Afrique' },
  'GB': { capital: 'Londres', population: 68.4, languages: 'Anglais', continent: 'Europe' },
  'GD': { capital: 'Saint-Georges', population: 0.1, languages: 'Anglais', continent: 'Amérique du Nord' },
  'GE': { capital: 'Tbilissi', population: 3.7, languages: 'Géorgien', continent: 'Asie' },
  'GH': { capital: 'Accra', population: 33.9, languages: 'Anglais', continent: 'Afrique' },
  'GM': { capital: 'Banjul', population: 2.6, languages: 'Anglais', continent: 'Afrique' },
  'GN': { capital: 'Conakry', population: 14.2, languages: 'Français', continent: 'Afrique' },
  'GQ': { capital: 'Malabo', population: 1.7, languages: 'Espagnol, Français', continent: 'Afrique' },
  'GR': { capital: 'Athènes', population: 10.4, languages: 'Grec', continent: 'Europe' },
  'GT': { capital: 'Guatemala', population: 18.1, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'GW': { capital: 'Bissau', population: 2.1, languages: 'Portugais', continent: 'Afrique' },
  'GY': { capital: 'Georgetown', population: 0.8, languages: 'Anglais', continent: 'Amérique du Sud' },
  'HN': { capital: 'Tegucigalpa', population: 10.4, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'HR': { capital: 'Zagreb', population: 3.9, languages: 'Croate', continent: 'Europe' },
  'HT': { capital: 'Port-au-Prince', population: 11.6, languages: 'Français, Créole', continent: 'Amérique du Nord' },
  'HU': { capital: 'Budapest', population: 9.7, languages: 'Hongrois', continent: 'Europe' },
  'ID': { capital: 'Jakarta', population: 277.5, languages: 'Indonésien', continent: 'Asie' },
  'IE': { capital: 'Dublin', population: 5.1, languages: 'Anglais, Irlandais', continent: 'Europe' },
  'IL': { capital: 'Jérusalem', population: 9.4, languages: 'Hébreu, Arabe', continent: 'Asie' },
  'IN': { capital: 'New Delhi', population: 1428.6, languages: 'Hindi, Anglais', continent: 'Asie' },
  'IQ': { capital: 'Bagdad', population: 45.5, languages: 'Arabe, Kurde', continent: 'Asie' },
  'IR': { capital: 'Téhéran', population: 89.2, languages: 'Persan', continent: 'Asie' },
  'IS': { capital: 'Reykjavik', population: 0.4, languages: 'Islandais', continent: 'Europe' },
  'IT': { capital: 'Rome', population: 58.9, languages: 'Italien', continent: 'Europe' },
  'JM': { capital: 'Kingston', population: 2.8, languages: 'Anglais', continent: 'Amérique du Nord' },
  'JO': { capital: 'Amman', population: 11.3, languages: 'Arabe', continent: 'Asie' },
  'JP': { capital: 'Tokyo', population: 123.3, languages: 'Japonais', continent: 'Asie' },
  'KE': { capital: 'Nairobi', population: 55.1, languages: 'Anglais, Swahili', continent: 'Afrique' },
  'KG': { capital: 'Bichkek', population: 7.0, languages: 'Kirghize, Russe', continent: 'Asie' },
  'KH': { capital: 'Phnom Penh', population: 17.4, languages: 'Khmer', continent: 'Asie' },
  'KI': { capital: 'Tarawa', population: 0.13, languages: 'Anglais', continent: 'Océanie' },
  'KM': { capital: 'Moroni', population: 0.9, languages: 'Comorien, Français, Arabe', continent: 'Afrique' },
  'KN': { capital: 'Basseterre', population: 0.05, languages: 'Anglais', continent: 'Amérique du Nord' },
  'KP': { capital: 'Pyongyang', population: 26.2, languages: 'Coréen', continent: 'Asie' },
  'KR': { capital: 'Séoul', population: 51.7, languages: 'Coréen', continent: 'Asie' },
  'KW': { capital: 'Koweït', population: 4.3, languages: 'Arabe', continent: 'Asie' },
  'KZ': { capital: 'Astana', population: 19.6, languages: 'Kazakh, Russe', continent: 'Asie' },
  'LA': { capital: 'Vientiane', population: 7.7, languages: 'Lao', continent: 'Asie' },
  'LB': { capital: 'Beyrouth', population: 5.4, languages: 'Arabe', continent: 'Asie' },
  'LC': { capital: 'Castries', population: 0.18, languages: 'Anglais', continent: 'Amérique du Nord' },
  'LI': { capital: 'Vaduz', population: 0.04, languages: 'Allemand', continent: 'Europe' },
  'LK': { capital: 'Colombo', population: 22.2, languages: 'Cinghalais, Tamoul', continent: 'Asie' },
  'LR': { capital: 'Monrovia', population: 5.3, languages: 'Anglais', continent: 'Afrique' },
  'LS': { capital: 'Maseru', population: 2.3, languages: 'Sesotho, Anglais', continent: 'Afrique' },
  'LT': { capital: 'Vilnius', population: 2.7, languages: 'Lituanien', continent: 'Europe' },
  'LU': { capital: 'Luxembourg', population: 0.66, languages: 'Luxembourgeois, Français, Allemand', continent: 'Europe' },
  'LV': { capital: 'Riga', population: 1.8, languages: 'Letton', continent: 'Europe' },
  'LY': { capital: 'Tripoli', population: 6.9, languages: 'Arabe', continent: 'Afrique' },
  'MA': { capital: 'Rabat', population: 37.8, languages: 'Arabe, Amazighe', continent: 'Afrique' },
  'MC': { capital: 'Monaco', population: 0.04, languages: 'Français', continent: 'Europe' },
  'MD': { capital: 'Chisinau', population: 2.5, languages: 'Roumain', continent: 'Europe' },
  'ME': { capital: 'Podgorica', population: 0.6, languages: 'Monténégrin', continent: 'Europe' },
  'MG': { capital: 'Antananarivo', population: 30.3, languages: 'Malgache, Français', continent: 'Afrique' },
  'MH': { capital: 'Majuro', population: 0.04, languages: 'Anglais, Marshallais', continent: 'Océanie' },
  'MK': { capital: 'Skopje', population: 2.1, languages: 'Macédonien', continent: 'Europe' },
  'ML': { capital: 'Bamako', population: 23.3, languages: 'Français', continent: 'Afrique' },
  'MM': { capital: 'Naypyidaw', population: 54.2, languages: 'Birman', continent: 'Asie' },
  'MN': { capital: 'Oulan-Bator', population: 3.4, languages: 'Mongol', continent: 'Asie' },
  'MR': { capital: 'Nouakchott', population: 4.9, languages: 'Arabe', continent: 'Afrique' },
  'MT': { capital: 'La Valette', population: 0.5, languages: 'Maltais, Anglais', continent: 'Europe' },
  'MU': { capital: 'Port-Louis', population: 1.3, languages: 'Anglais, Français', continent: 'Afrique' },
  'MV': { capital: 'Malé', population: 0.5, languages: 'Divehi', continent: 'Asie' },
  'MW': { capital: 'Lilongwe', population: 20.9, languages: 'Anglais, Chichewa', continent: 'Afrique' },
  'MX': { capital: 'Mexico', population: 128.5, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'MY': { capital: 'Kuala Lumpur', population: 34.3, languages: 'Malais', continent: 'Asie' },
  'MZ': { capital: 'Maputo', population: 33.9, languages: 'Portugais', continent: 'Afrique' },
  'NA': { capital: 'Windhoek', population: 2.6, languages: 'Anglais', continent: 'Afrique' },
  'NE': { capital: 'Niamey', population: 27.2, languages: 'Français', continent: 'Afrique' },
  'NG': { capital: 'Abuja', population: 223.8, languages: 'Anglais', continent: 'Afrique' },
  'NI': { capital: 'Managua', population: 6.9, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'NL': { capital: 'Amsterdam', population: 17.9, languages: 'Néerlandais', continent: 'Europe' },
  'NO': { capital: 'Oslo', population: 5.5, languages: 'Norvégien', continent: 'Europe' },
  'NP': { capital: 'Katmandou', population: 30.3, languages: 'Népalais', continent: 'Asie' },
  'NR': { capital: 'Yaren', population: 0.01, languages: 'Nauruan, Anglais', continent: 'Océanie' },
  'NZ': { capital: 'Wellington', population: 5.2, languages: 'Anglais', continent: 'Océanie' },
  'OM': { capital: 'Mascate', population: 4.6, languages: 'Arabe', continent: 'Asie' },
  'PA': { capital: 'Panama', population: 4.4, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'PE': { capital: 'Lima', population: 34.4, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'PG': { capital: 'Port Moresby', population: 10.3, languages: 'Anglais', continent: 'Océanie' },
  'PH': { capital: 'Manille', population: 117.3, languages: 'Filipino, Anglais', continent: 'Asie' },
  'PK': { capital: 'Islamabad', population: 240.5, languages: 'Ourdou, Anglais', continent: 'Asie' },
  'PL': { capital: 'Varsovie', population: 37.8, languages: 'Polonais', continent: 'Europe' },
  'PS': { capital: 'Ramallah', population: 5.2, languages: 'Arabe', continent: 'Asie' },
  'PT': { capital: 'Lisbonne', population: 10.3, languages: 'Portugais', continent: 'Europe' },
  'PW': { capital: 'Ngerulmud', population: 0.02, languages: 'Palaosien, Anglais', continent: 'Océanie' },
  'PY': { capital: 'Asuncion', population: 6.9, languages: 'Espagnol, Guarani', continent: 'Amérique du Sud' },
  'QA': { capital: 'Doha', population: 2.7, languages: 'Arabe', continent: 'Asie' },
  'RO': { capital: 'Bucarest', population: 19.1, languages: 'Roumain', continent: 'Europe' },
  'RS': { capital: 'Belgrade', population: 6.6, languages: 'Serbe', continent: 'Europe' },
  'RU': { capital: 'Moscou', population: 143.8, languages: 'Russe', continent: 'Europe' },
  'RW': { capital: 'Kigali', population: 13.8, languages: 'Kinyarwanda, Français, Anglais', continent: 'Afrique' },
  'SA': { capital: 'Riyad', population: 36.9, languages: 'Arabe', continent: 'Asie' },
  'SB': { capital: 'Honiara', population: 0.7, languages: 'Anglais', continent: 'Océanie' },
  'SC': { capital: 'Victoria', population: 0.1, languages: 'Créole, Anglais, Français', continent: 'Afrique' },
  'SD': { capital: 'Khartoum', population: 48.1, languages: 'Arabe', continent: 'Afrique' },
  'SE': { capital: 'Stockholm', population: 10.6, languages: 'Suédois', continent: 'Europe' },
  'SG': { capital: 'Singapour', population: 5.9, languages: 'Anglais, Malais, Mandarin, Tamoul', continent: 'Asie' },
  'SI': { capital: 'Ljubljana', population: 2.1, languages: 'Slovène', continent: 'Europe' },
  'SK': { capital: 'Bratislava', population: 5.4, languages: 'Slovaque', continent: 'Europe' },
  'SL': { capital: 'Freetown', population: 8.8, languages: 'Anglais', continent: 'Afrique' },
  'SM': { capital: 'Saint-Marin', population: 0.03, languages: 'Italien', continent: 'Europe' },
  'SN': { capital: 'Dakar', population: 17.8, languages: 'Français', continent: 'Afrique' },
  'SO': { capital: 'Mogadiscio', population: 18.1, languages: 'Somali, Arabe', continent: 'Afrique' },
  'SR': { capital: 'Paramaribo', population: 0.6, languages: 'Néerlandais', continent: 'Amérique du Sud' },
  'SS': { capital: 'Juba', population: 11.1, languages: 'Anglais', continent: 'Afrique' },
  'ST': { capital: 'Sao Tomé', population: 0.2, languages: 'Portugais', continent: 'Afrique' },
  'SV': { capital: 'San Salvador', population: 6.3, languages: 'Espagnol', continent: 'Amérique du Nord' },
  'SY': { capital: 'Damas', population: 23.2, languages: 'Arabe', continent: 'Asie' },
  'SZ': { capital: 'Mbabane', population: 1.2, languages: 'Anglais, Swati', continent: 'Afrique' },
  'TD': { capital: "N'Djamena", population: 18.3, languages: 'Français, Arabe', continent: 'Afrique' },
  'TG': { capital: 'Lomé', population: 8.8, languages: 'Français', continent: 'Afrique' },
  'TH': { capital: 'Bangkok', population: 71.6, languages: 'Thaï', continent: 'Asie' },
  'TJ': { capital: 'Douchanbé', population: 10.1, languages: 'Tadjik', continent: 'Asie' },
  'TL': { capital: 'Dili', population: 1.3, languages: 'Tétum, Portugais', continent: 'Asie' },
  'TM': { capital: 'Achgabat', population: 6.4, languages: 'Turkmène', continent: 'Asie' },
  'TN': { capital: 'Tunis', population: 12.3, languages: 'Arabe', continent: 'Afrique' },
  'TO': { capital: "Nuku'alofa", population: 0.1, languages: 'Tongien, Anglais', continent: 'Océanie' },
  'TR': { capital: 'Ankara', population: 85.8, languages: 'Turc', continent: 'Asie' },
  'TT': { capital: "Port-d'Espagne", population: 1.5, languages: 'Anglais', continent: 'Amérique du Nord' },
  'TV': { capital: 'Funafuti', population: 0.01, languages: 'Tuvaluan, Anglais', continent: 'Océanie' },
  'TW': { capital: 'Taipei', population: 23.6, languages: 'Mandarin', continent: 'Asie' },
  'TZ': { capital: 'Dodoma', population: 67.4, languages: 'Swahili, Anglais', continent: 'Afrique' },
  'UA': { capital: 'Kiev', population: 36.7, languages: 'Ukrainien', continent: 'Europe' },
  'UG': { capital: 'Kampala', population: 48.6, languages: 'Anglais, Swahili', continent: 'Afrique' },
  'US': { capital: 'Washington D.C.', population: 334.9, languages: 'Anglais', continent: 'Amérique du Nord' },
  'UY': { capital: 'Montevideo', population: 3.4, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'UZ': { capital: 'Tachkent', population: 35.6, languages: 'Ouzbek', continent: 'Asie' },
  'VA': { capital: 'Cité du Vatican', population: 0.0008, languages: 'Italien, Latin', continent: 'Europe' },
  'VC': { capital: 'Kingstown', population: 0.1, languages: 'Anglais', continent: 'Amérique du Nord' },
  'VE': { capital: 'Caracas', population: 28.3, languages: 'Espagnol', continent: 'Amérique du Sud' },
  'VN': { capital: 'Hanoï', population: 98.9, languages: 'Vietnamien', continent: 'Asie' },
  'VU': { capital: 'Port-Vila', population: 0.33, languages: 'Bichlamar, Anglais, Français', continent: 'Océanie' },
  'WS': { capital: 'Apia', population: 0.2, languages: 'Samoan, Anglais', continent: 'Océanie' },
  'YE': { capital: 'Sanaa', population: 34.4, languages: 'Arabe', continent: 'Asie' },
  'ZA': { capital: 'Pretoria', population: 60.4, languages: 'Anglais, Zoulou, Afrikaans (+ 8 autres)', continent: 'Afrique' },
  'ZM': { capital: 'Lusaka', population: 20.6, languages: 'Anglais', continent: 'Afrique' },
  'ZW': { capital: 'Harare', population: 16.3, languages: 'Anglais', continent: 'Afrique' },
};
